base_root_dir = "."

include = ["**/*"]
exclude = ["target/**/*", "examples/**/*", ".bough/**"]

workers = 8

init.cmd = "cargo build"
test.cmd = "cargo nextest run"

timeout.relative = 3.0

[env]
CARGO_BUILD_JOBS = 1
NEXTEST_TEST_THREADS = 1

[lang.rs]
include = [
  "crates/**/*.rs",
]

exclude = [
  "crates/bough-cli-tests/**/*",
  "crates/bough-corpus-tests/**/*",
  "crates/bough-typed-hash-derive/**/*",
]

[lang.rs.skip]
query = [
  """
(mod_item
  (attributes
    (attribute_item
      (attribute
        (identifier) @_attr_name
        (token_tree
          (identifier) @_attr_arg))))
  (#eq? @_attr_name "cfg")
  (#eq? @_attr_arg "test")) @skip
""",
]
