base_root_dir = "."

include = ["**/*"]
exclude = ["target/**/*", "examples/**/*"]

workers = 8

init.cmd = "cargo build"
test.cmd = "cargo nextest run"

[env]
CARGO_BUILD_JOBS = 1
NEXTEST_TEST_THREADS = 1

[lang.rs]
include = [
  "crates/bough-core/**/*.rs",
  "crates/bough-cli/**/*.rs",
  "crates/bough-typed-hash/**/*.rs",
]

[lang.rs.skip]
query = [
  """
(mod_item
  (attributes
    (attribute_item
      (attribute
        (identifier) @_attr_name
        (token_tree
          (identifier) @_attr_arg))))
  (#eq? @_attr_name "cfg")
  (#eq? @_attr_arg "test")) @skip
""",
]
