[[mutation]]
kind = "StatementBlock"
snippet = """
void f() { x = 1; }"""

[[mutation]]
kind = "Condition"
snippet = """
void f() { if (x) { return; } }"""

[[mutation]]
kind = "BinaryOp(Add)"
snippet = """
int x = a + b;"""

[[mutation]]
kind = "BinaryOp(And)"
snippet = """
int x = a && b;"""

[[mutation]]
kind = "BinaryOp(BitAnd)"
snippet = """
int x = a & b;"""

[[mutation]]
kind = "BinaryOp(BitOr)"
snippet = """
int x = a | b;"""

[[mutation]]
kind = "BinaryOp(BitXor)"
snippet = """
int x = a ^ b;"""

[[mutation]]
kind = "BinaryOp(Div)"
snippet = """
int x = a / b;"""

[[mutation]]
kind = "BinaryOp(Eq)"
snippet = """
int x = a == b;"""

[[mutation]]
kind = "BinaryOp(Gt)"
snippet = """
int x = a > b;"""

[[mutation]]
kind = "BinaryOp(Gte)"
snippet = """
int x = a >= b;"""

[[mutation]]
kind = "BinaryOp(Lt)"
snippet = """
int x = a < b;"""

[[mutation]]
kind = "BinaryOp(Lte)"
snippet = """
int x = a <= b;"""

[[mutation]]
kind = "BinaryOp(Mul)"
snippet = """
int x = a * b;"""

[[mutation]]
kind = "BinaryOp(Or)"
snippet = """
int x = a || b;"""

[[mutation]]
kind = "BinaryOp(Rem)"
snippet = """
int x = a % b;"""

[[mutation]]
kind = "BinaryOp(Shl)"
snippet = """
int x = a << b;"""

[[mutation]]
kind = "BinaryOp(Shr)"
snippet = """
int x = a >> b;"""

[[mutation]]
kind = "BinaryOp(Ne)"
snippet = """
int x = a != b;"""

[[mutation]]
kind = "BinaryOp(Sub)"
snippet = """
int x = a - b;"""

[[mutation]]
kind = "Assign(AddAssign)"
snippet = """
void f() { x += 1; }"""

[[mutation]]
kind = "Assign(BitAndAssign)"
snippet = """
void f() { x &= 1; }"""

[[mutation]]
kind = "Assign(BitOrAssign)"
snippet = """
void f() { x |= 1; }"""

[[mutation]]
kind = "Assign(BitXorAssign)"
snippet = """
void f() { x ^= 1; }"""

[[mutation]]
kind = "Assign(DivAssign)"
snippet = """
void f() { x /= 1; }"""

[[mutation]]
kind = "Assign(MulAssign)"
snippet = """
void f() { x *= 1; }"""

[[mutation]]
kind = "Assign(NormalAssign)"
snippet = """
void f() { x = 1; }"""

[[mutation]]
kind = "Assign(RemAssign)"
snippet = """
void f() { x %= 1; }"""

[[mutation]]
kind = "Assign(ShlAssign)"
snippet = """
void f() { x <<= 1; }"""

[[mutation]]
kind = "Assign(ShrAssign)"
snippet = """
void f() { x >>= 1; }"""

[[mutation]]
kind = "Assign(SubAssign)"
snippet = """
void f() { x -= 1; }"""

[[mutation]]
kind = "ArrayDecl(Inline)"
snippet = """
int arr[] = {1, 2, 3};"""

[[mutation]]
kind = "Literal(String)"
snippet = """
char *s = "hello";"""

[[mutation]]
kind = "Literal(EmptyString)"
snippet = """
char *s = "";"""

[[mutation]]
kind = "Literal(Number)"
snippet = """
int x = 42;"""

[[mutation]]
kind = "UnaryNot"
snippet = """
void f() { int x = !y; }"""

[[mutation]]
kind = "SwitchCase"
snippet = """
void f() { switch(x) { case 1: break; } }"""

