[[mutation]]
kind = "StatementBlock"
snippet = """
if (x) { y(); }"""

[[mutation]]
kind = "Condition"
snippet = """
if (x) { y(); }"""

[[mutation]]
kind = "BinaryOp(Add)"
snippet = """
const x = 1 + 2"""

[[mutation]]
kind = "BinaryOp(And)"
snippet = """
const x = a && b"""

[[mutation]]
kind = "BinaryOp(BitAnd)"
snippet = """
const x = 1 & 2"""

[[mutation]]
kind = "BinaryOp(BitOr)"
snippet = """
const x = 1 | 2"""

[[mutation]]
kind = "BinaryOp(BitXor)"
snippet = """
const x = 1 ^ 2"""

[[mutation]]
kind = "BinaryOp(Div)"
snippet = """
const x = 1 / 2"""

[[mutation]]
kind = "BinaryOp(Eq)"
snippet = """
const x = a == b"""

[[mutation]]
kind = "BinaryOp(Gt)"
snippet = """
const x = a > b"""

[[mutation]]
kind = "BinaryOp(Gte)"
snippet = """
const x = a >= b"""

[[mutation]]
kind = "BinaryOp(Lt)"
snippet = """
const x = a < b"""

[[mutation]]
kind = "BinaryOp(Lte)"
snippet = """
const x = a <= b"""

[[mutation]]
kind = "BinaryOp(Mul)"
snippet = """
const x = 1 * 2"""

[[mutation]]
kind = "BinaryOp(Or)"
snippet = """
const x = a || b"""

[[mutation]]
kind = "BinaryOp(Rem)"
snippet = """
const x = 1 % 2"""

[[mutation]]
kind = "BinaryOp(Shl)"
snippet = """
const x = 1 << 2"""

[[mutation]]
kind = "BinaryOp(Shr)"
snippet = """
const x = 1 >> 2"""

[[mutation]]
kind = "BinaryOp(StrictEq)"
snippet = """
const x = a === b"""

[[mutation]]
kind = "BinaryOp(Ne)"
snippet = """
const x = a != b"""

[[mutation]]
kind = "BinaryOp(StrictNe)"
snippet = """
const x = a !== b"""

[[mutation]]
kind = "BinaryOp(Sub)"
snippet = """
const x = 1 - 2"""

[[mutation]]
kind = "Assign(AddAssign)"
snippet = """
x += 1"""

[[mutation]]
kind = "Assign(AndAssign)"
snippet = """
x &&= 1"""

[[mutation]]
kind = "Assign(BitAndAssign)"
snippet = """
x &= 1"""

[[mutation]]
kind = "Assign(BitOrAssign)"
snippet = """
x |= 1"""

[[mutation]]
kind = "Assign(BitXorAssign)"
snippet = """
x ^= 1"""

[[mutation]]
kind = "Assign(DivAssign)"
snippet = """
x /= 1"""

[[mutation]]
kind = "Assign(MulAssign)"
snippet = """
x *= 1"""

[[mutation]]
kind = "Assign(NormalAssign)"
snippet = """
x = 1"""

[[mutation]]
kind = "Assign(OrAssign)"
snippet = """
x ||= 1"""

[[mutation]]
kind = "Assign(RemAssign)"
snippet = """
x %= 1"""

[[mutation]]
kind = "Assign(ShlAssign)"
snippet = """
x <<= 1"""

[[mutation]]
kind = "Assign(ShrAssign)"
snippet = """
x >>= 1"""

[[mutation]]
kind = "Assign(SubAssign)"
snippet = """
x -= 1"""

[[mutation]]
kind = "ArrayDecl(Inline)"
snippet = """
[1,2,3]"""

[[mutation]]
kind = "ArrayDecl(Instance)"
snippet = """
new Array(1, 2, 3)"""

[[mutation]]
kind = "Literal(BoolTrue)"
snippet = """
true"""

[[mutation]]
kind = "Literal(BoolFalse)"
snippet = """
false"""

[[mutation]]
kind = "Literal(String)"
snippet = """
'foo'"""

[[mutation]]
kind = "Literal(EmptyString)"
snippet = """
''"""

[[mutation]]
kind = "Literal(Number)"
snippet = """
123"""

[[mutation]]
kind = "DictDecl"
snippet = """
const x = {foo: 1, bar: null}"""

[[mutation]]
kind = "OptionalChain(Literal)"
snippet = """
const x = y?.z"""

[[mutation]]
kind = "OptionalChain(Indexed)"
snippet = """
const x = y?.['z']"""

[[mutation]]
kind = "OptionalChain(FnCall)"
snippet = """
const x = y?.()"""

[[mutation]]
kind = "SwitchCase"
snippet = """
switch (x) {
  case 1:
    foo();
    break;

  case 2: {
    bar();
    break;
  }

  default: {
    baz();
    break;
  }
}"""

