[[mutation]]
kind = "StatementBlock"
snippet = """
def foo
  puts "hello"
end"""

[[mutation]]
kind = "Condition"
snippet = """
if x > 0
  puts x
end"""

[[mutation]]
kind = "BinaryOp(Add)"
snippet = """
x = a + b"""

[[mutation]]
kind = "BinaryOp(Sub)"
snippet = """
x = a - b"""

[[mutation]]
kind = "BinaryOp(Mul)"
snippet = """
x = a * b"""

[[mutation]]
kind = "BinaryOp(Div)"
snippet = """
x = a / b"""

[[mutation]]
kind = "BinaryOp(Rem)"
snippet = """
x = a % b"""

[[mutation]]
kind = "BinaryOp(Eq)"
snippet = """
x = a == b"""

[[mutation]]
kind = "BinaryOp(Ne)"
snippet = """
x = a != b"""

[[mutation]]
kind = "BinaryOp(Gt)"
snippet = """
x = a > b"""

[[mutation]]
kind = "BinaryOp(Gte)"
snippet = """
x = a >= b"""

[[mutation]]
kind = "BinaryOp(Lt)"
snippet = """
x = a < b"""

[[mutation]]
kind = "BinaryOp(Lte)"
snippet = """
x = a <= b"""

[[mutation]]
kind = "BinaryOp(And)"
snippet = """
x = a && b"""

[[mutation]]
kind = "BinaryOp(Or)"
snippet = """
x = a || b"""

[[mutation]]
kind = "BinaryOp(BitAnd)"
snippet = """
x = a & b"""

[[mutation]]
kind = "BinaryOp(BitOr)"
snippet = """
x = a | b"""

[[mutation]]
kind = "BinaryOp(BitXor)"
snippet = """
x = a ^ b"""

[[mutation]]
kind = "BinaryOp(Shl)"
snippet = """
x = a << b"""

[[mutation]]
kind = "BinaryOp(Shr)"
snippet = """
x = a >> b"""

[[mutation]]
kind = "Assign(NormalAssign)"
snippet = """
x = y"""

[[mutation]]
kind = "Assign(AddAssign)"
snippet = """
x += y"""

[[mutation]]
kind = "Assign(SubAssign)"
snippet = """
x -= y"""

[[mutation]]
kind = "Assign(MulAssign)"
snippet = """
x *= y"""

[[mutation]]
kind = "Assign(DivAssign)"
snippet = """
x /= y"""

[[mutation]]
kind = "Assign(RemAssign)"
snippet = """
x %= y"""

[[mutation]]
kind = "Assign(BitAndAssign)"
snippet = """
x &= y"""

[[mutation]]
kind = "Assign(BitOrAssign)"
snippet = """
x |= y"""

[[mutation]]
kind = "Assign(BitXorAssign)"
snippet = """
x ^= y"""

[[mutation]]
kind = "Assign(ShlAssign)"
snippet = """
x <<= y"""

[[mutation]]
kind = "Assign(ShrAssign)"
snippet = """
x >>= y"""

[[mutation]]
kind = "ArrayDecl(Inline)"
snippet = """
x = [1, 2, 3]"""

[[mutation]]
kind = "Literal(BoolTrue)"
snippet = """
x = true"""

[[mutation]]
kind = "Literal(BoolFalse)"
snippet = """
x = false"""

[[mutation]]
kind = "Literal(String)"
snippet = """
x = "hello"
"""

[[mutation]]
kind = "Literal(EmptyString)"
snippet = """
x = ""
"""

[[mutation]]
kind = "Literal(Number)"
snippet = """
x = 42"""

[[mutation]]
kind = "DictDecl"
snippet = """
x = {a: 1, b: 2}"""

[[mutation]]
kind = "UnaryNot"
snippet = """
x = !y"""

[[mutation]]
kind = "SwitchCase"
snippet = """
case x
when 1
  "one"
when 2
  "two"
end"""
