[[mutation]]
kind = "StatementBlock"
snippet = """
if x > 0 { }"""

[[mutation]]
kind = "Condition"
snippet = """
if x > 0 { }"""

[[mutation]]
kind = "BinaryOp(Add)"
snippet = """
let x = a + b;"""

[[mutation]]
kind = "BinaryOp(And)"
snippet = """
let x = a && b;"""

[[mutation]]
kind = "BinaryOp(BitAnd)"
snippet = """
let x = a & b;"""

[[mutation]]
kind = "BinaryOp(BitOr)"
snippet = """
let x = a | b;"""

[[mutation]]
kind = "BinaryOp(BitXor)"
snippet = """
let x = a ^ b;"""

[[mutation]]
kind = "BinaryOp(Div)"
snippet = """
let x = a / b;"""

[[mutation]]
kind = "BinaryOp(Eq)"
snippet = """
let x = a == b;"""

[[mutation]]
kind = "BinaryOp(Gt)"
snippet = """
if x > 0 { }"""

[[mutation]]
kind = "BinaryOp(Gte)"
snippet = """
let x = a >= b;"""

[[mutation]]
kind = "BinaryOp(Lt)"
snippet = """
let x = a < b;"""

[[mutation]]
kind = "BinaryOp(Lte)"
snippet = """
let x = a <= b;"""

[[mutation]]
kind = "BinaryOp(Mul)"
snippet = """
let x = a * b;"""

[[mutation]]
kind = "BinaryOp(Or)"
snippet = """
let x = a || b;"""

[[mutation]]
kind = "BinaryOp(Rem)"
snippet = """
let x = a % b;"""

[[mutation]]
kind = "BinaryOp(Shl)"
snippet = """
let x = a << b;"""

[[mutation]]
kind = "BinaryOp(Shr)"
snippet = """
let x = a >> b;"""

[[mutation]]
kind = "BinaryOp(Ne)"
snippet = """
let x = a != b;"""

[[mutation]]
kind = "BinaryOp(Sub)"
snippet = """
let x = a - b;"""

[[mutation]]
kind = "Assign(AddAssign)"
snippet = """
x += 1;"""

[[mutation]]
kind = "Assign(BitAndAssign)"
snippet = """
x &= 1;"""

[[mutation]]
kind = "Assign(BitOrAssign)"
snippet = """
x |= 1;"""

[[mutation]]
kind = "Assign(BitXorAssign)"
snippet = """
x ^= 1;"""

[[mutation]]
kind = "Assign(DivAssign)"
snippet = """
x /= 1;"""

[[mutation]]
kind = "Assign(MulAssign)"
snippet = """
x *= 1;"""

[[mutation]]
kind = "Assign(NormalAssign)"
snippet = """
x = 1;"""

[[mutation]]
kind = "Assign(RemAssign)"
snippet = """
x %= 1;"""

[[mutation]]
kind = "Assign(ShlAssign)"
snippet = """
x <<= 1;"""

[[mutation]]
kind = "Assign(ShrAssign)"
snippet = """
x >>= 1;"""

[[mutation]]
kind = "Assign(SubAssign)"
snippet = """
x -= 1;"""

[[mutation]]
kind = "ArrayDecl(Inline)"
snippet = """
let x = [1, 2, 3];"""

[[mutation]]
kind = "Literal(BoolTrue)"
snippet = """
let x = true;"""

[[mutation]]
kind = "Literal(BoolFalse)"
snippet = """
let x = false;"""

[[mutation]]
kind = "Literal(String)"
snippet = """
let x = "hello";"""

[[mutation]]
kind = "Literal(EmptyString)"
snippet = """
let x = "";"""

[[mutation]]
kind = "Literal(Number)"
snippet = """
x = 1;"""

[[mutation]]
kind = "TupleDecl"
snippet = """
let x = (1, 2, 3);"""

[[mutation]]
kind = "UnaryNot"
snippet = """
let x = !y;"""

[[mutation]]
kind = "SwitchCase"
snippet = """
match x {
    n if n > 5 => n,
    _ => 2,
}"""

[[mutation]]
kind = "Range(Exclusive)"
snippet = """
let x = ..5;"""

[[mutation]]
kind = "Range(Inclusive)"
snippet = """
let x = ..=5;"""

[[mutation]]
kind = "Range(From)"
snippet = """
let x = 1..;"""

[[mutation]]
kind = "MatchPattern"
snippet = """
match x {
    1 => println!("one"),
    _ => println!("other"),
}"""

