threads = 1
bough_dir = "./.bough"

[vitest]
ordering = "alphabetical"
treat_timeouts_as = "Missed"

[vitest.init]
pwd = "./examples/vitest"
commands = ["npm install"]

[vitest.reset]
pwd = "./examples/vitest"
commands = ["npm clean"]

[vitest.test]
pwd = "./examples/vitest"
timeout.absolute = 30
timeout.relative = 3
env = { NODE_ENV = "production" }
commands = [
  "npx run build",
  "npx run test",
]

[vitest.mutate.js]
files.include = ["**/*.js", "**/*.jsx"]
files.exclude = ["**/*__mocks__*"]
mutants.skip = [
  { query = "((fn 'describe') @ignore)" } ,
  { kind = { "BinaryOp" = "Add" } }
]

[vitest.mutate.ts]
files.include = ["**/*.rs"]
mutants.skip = [
  { query = "((condition'describe') @ignore)" } ,
  { kind = { "BinaryOp" = "Add" } }
]

[cargo]
pwd = "./examples/cargo"

[cargo.test]
timeout.absolute = 30
timeout.relative = 3
commands = ["cargo test"]

[cargo.mutate.js]
files.include = ["**/*.js", "**/*.jsx"]
files.exclude = ["**/*__mocks__*"]
mutants.skip = [
  { query = "((fn 'describe') @ignore)" } ,
  { kind = { "BinaryOp" = "Add" } }
]

[cargo.mutate.ts]
files.include = ["**/*.rs"]
mutants.skip = [
  { query = "((fn 'describe') @ignore)" } ,
  { kind = { "BinaryOp" = "Add" } }
]
