include = ["**/*"]
exclude = ["**/node_modules/**"]

base_root_dir = "../"

init.cmd = "npm install"
test.cmd = "npm run test"

[lang.js]
include = [
  "src/**/*.js",
  "src/**/*.jsx",
]
exclude = ["**/*.test.*"]
